### ISSUE TITLE
Search optimisations

### ISSUE THREAD

**Issue by ghost** [adfinis-sygroup/finja#1]
`finja readlines for in -> fast`

`finja for in readlines -> slow`

It seems SQLite doesn't optimise join orders.

**Comment by winged** [comment]
Seems so, yes... You could try getting a `count()` on all involved tokens first, and order the `JOIN` statements accordingly. Still possible that it could be slow if the statistics don't match the resulting files, but it should pose an improved overall performance (at the cost of some initial overhead to build the statistics)

**Comment by ghost** [comment]
The big question: is a count() as slow as doing the actual search for the token?

**Comment by winged** [comment]
To answer your question: `count()` is pretty fast :)

**Comment by ghost** [comment]
Tested: works.
