### ISSUE TITLE
Implement --file-list -l

### ISSUE THREAD

**Issue by ghost** [adfinis-sygroup/finja#2]
`finja -l path/to/file`

Should copy the file to FINJA.lst along with the database

`generate-filelist | finja -l -`

Should read the file-list from stdin and store it at FINJA.lst

See:
https://github.com/adfinis-sygroup/finja/commit/8db40661dea3c426cd793fa29e8f60133814b88c#commitcomment-15513128

**Comment by winged** [comment]
Just had an idea: Please support NUL-byte separation as an option as well, so we can properly handle filenames with spaces in them.. similar to `find -print0` or `xargs -0`

Alternatively, if we separate files strictly by newline, we may not have this problem in the first place.. but still wanted to drop that idea :)

**Comment by ghost** [comment]
This is implemented in --raw. But we might change its name?

**Comment by ghost** [comment]
Stale, close
